language: go
go: 1.9.x

branches:
    only:
        - master
        - develop
jobs:
    include:
        - stage: lint
          script:
              - ./ci/validate-gofmt.sh
              - go get -u golang.org/x/lint/golint
              - ./ci/validate-lint.sh 2>&1 >/dev/null |  grep -vE "_mock|_test"
        - stage: test
          script: go test -p 1 github.com/spacemeshos/go-spacemesh/...
