language: go
go: 1.9.x


before_install:
- bash ci/install-protobuf.sh
- GIT_TAG="v1.2.0" # change as needed
- go get -d -u github.com/golang/protobuf/protoc-gen-go
- git -C "$(go env GOPATH)"/src/github.com/golang/protobuf checkout $GIT_TAG
- go install github.com/golang/protobuf/protoc-gen-go
- protoc --version
- bash ci/genproto.sh

branches:
  only:
  - master
  - develop
jobs:
  include:
  - stage: lint
    script:
    - make lint
  - stage: test
    script:
    - make devtools
    - make test
