language: go
sudo: false
go: 1.11.x

env: GO111MODULE=on

# for some reason /usr/local is owned by a different user in travis, so we transfer ownership to the current user:
before_install: sudo chown -R $(whoami) /usr/local

install: make install

branches:
  only:
  - develop

jobs:
  include:
  - stage: lint
    install: true # this skips the installation step
    script: make lint
  - stage: test
    script:
      - make genproto
      - make test
  - stage: tidy
    script:
      - make genproto
      - make test-tidy

cache:
  directories:
    - $GOPATH/pkg/mod
