language: go
sudo: false
go: 1.11.x

env:
  - GO111MODULE=on

before_install:
  - sudo find /usr/local -exec chmod a+w {} \;
  - make prepare

branches:
  only:
  - develop
jobs:
  include:
  - stage: lint
    script:
      - make lint
  - stage: test
    script:
      - make genproto
      - make test

cache:
  directories:
    - $GOPATH/pkg/mod
