language: go
sudo: false
go: 1.11.x

env:
  - GO111MODULE=on

before_install:
  # for some reason /usr/local is owned by a different user in travis, so we transfer ownership to the current user:
  - sudo chown -R $(whoami) /usr/local
  - make prepare

branches:
  only:
  - develop
jobs:
  include:
  - stage: lint
    script:
      - make lint
  - stage: test
    script:
      - make genproto
      - make test

cache:
  directories:
    - $GOPATH/pkg/mod
