language: go
go: 1.9.x


before_install:
- sudo apt-get install protobuf-compiler
- bash ci/genproto.sh

branches:
  only:
  - master
  - develop
jobs:
  include:
  - stage: lint
    script:
    - make devtools
    - make lint
  - stage: test
    script:
    - make devtools
    - make test
