language: go
go: 1.9.x

branches:
    only:
        - master
        - develop
jobs:
    include:
        - stage: test
          script:
            - make devtools
            - go test -p 1 github.com/spacemeshos/go-spacemesh/...
